### ISSUE TITLE
Create a common class to take input for command prompt and return result

### ISSUE THREAD

**Issue by chavarera** [chavarera/Cinfo#16]
Create class CommandHandler.py in common and create method to accept user input and return processed result on command or terminal

Required module: subprocess

**Comment by david-ash** [comment]
I would like to work on the issue, what type of input user can give and what will be the returned result?

**Comment by chavarera** [comment]
Like if user enter 
ipconfig it should return 
Command prompt result

**Comment by chavarera** [comment]
User command type
cmd='wmic CPU get Name,NumberOfCores,NumberOfLogicalProcessors'

It will give  command prompt result about system info

**Comment by david-ash** [comment]
Can you provide me any resource which can help in my start?

**Comment by chavarera** [comment]
@david-ash  Check this is simple Command Handler https://github.com/chavarera/Cinfo/blob/master/lib/windows/common/CommandHandler.py

**Comment by david-ash** [comment]
yes, i will complete this work as soon as i can

**Comment by chavarera** [comment]
@david-ash i just created a simple code you can add more advanced with Error Handeer
